---
title: "Title"
format:
  docx: default
editor_options: 
  chunk_output_type: console
execute:
  freeze: auto  # re-render only when source changes
  cache: false
  echo: false
  warning: false
  error: false
  include: true
crossref:
  fig-title: 'Figure'
  fig-labels: arabic
  title-delim: "-"
  fig-prefix: "Figure"
  tbl-prefix: "Table"
---

```{r}
#| label: setup

pacman::p_load(tidyverse, flextable, here, dplyr, tidyselect, brms)
source(here::here("R", "func.R"))
```
# Main Manuscript Tables

## Morphology

@tbl-tbl1

```{r, tbl-tbl1}
#| label: tbl-tbl1
#| tbl-cap: Posterior means and 95% credible intervals for the interaction between temperature (Temp) and maternal investment (Invest) along with the main effects of temperature and maternal investment on mophological traits for *Lampropholis delicata* and *Lampropholis guichenoti*. Main effects are pooled posterior means over each level of second predictor variable.

	# Bring in models
		deli_morph_int <- readRDS(here::here("output/models/", "deli_morph_int.rds"))
	   guich_morph_int <- readRDS(here::here("output/models/", "guich_morph_int.rds"))

	# Build tables
		 deli <- build_morph_table(deli_morph_int)  %>% mutate(Species = c("L. delicata", rep("", 8)),
		 													   Trait = c("SVL", rep("", 2), "Weight", rep("",2), "Tail", rep("",2)))  %>% select(Species, Trait, contrast, Estimate, Q2.5, Q97.5,pmcmc)  %>%  mutate(dplyr::across(tidyselect::where(is.numeric), round, 3))
		guich <- build_morph_table(guich_morph_int) %>% mutate(Species = c("L. guichenoti", rep("", 8)),
		 													   Trait = c("SVL", rep("", 2), "Weight", rep("",2), "Tail", rep("",2)))  %>% select(Species, Trait, contrast, Estimate, Q2.5, Q97.5,pmcmc)   %>%  mutate(dplyr::across(tidyselect::where(is.numeric), round, 3))
	
	# Full table
		full <- rbind(deli, guich)
	flextable(full)  %>% autofit()  %>% align(align = "center", part = "all")  
```

## Performance and Behaviour

@tbl-tbl2 

@tbl-tblS3

```{r, tbl-tbl2}
#| label: tbl-tbl2
#| tbl-cap: Posterior means and 95% credible intervals for the interaction between temperature (Temp) and maternal investment (Invest) along with the main effects of temperature and maternal investment on behavioural and performance traits for *Lampropholis delicata* and *Lampropholis guichenoti*. Main effects are pooled posterior means over each level of second predictor variable. Estimates are from a Bayesian multivariate (multi-response) model not controlling for SVL.

# Load models
   deli_behav_int_nonSVL <- readRDS(here::here("output/models/", "deli_behav_int_nonSVL.rds"))
	 guich_mv_int_nonSVL <- readRDS(here::here("output/models/", "guich_mv_int_nonSVL.rds"))

# Build tables
	 deli_behav <- build_behav_table(deli_behav_int_nonSVL)  %>% 
	 				mutate(Species = c("L. delicata", rep("", 14)),
						Trait = c("log Emergence Time (s)", rep("", 2),
								  "log Time Snout Out (s)", rep("", 2), 
								  "Distance Moved (cm)", rep("", 2), 
								  "log 1m Speed (cm/s)", rep("", 2),
								  "log Burst Speed (cm/s)", rep("", 2)))  %>% 
					select(Species, Trait, contrast, Estimate, Q2.5, Q97.5,pmcmc)
	guich_behav <- build_behav_table(guich_mv_int_nonSVL)  %>% 
					mutate(Species = c("L. guichenoti", rep("", 14)),
							Trait = c("log Emergence Time (s)", rep("", 2),
								      "log Time Snout Out (s)", rep("", 2), 
								      "Distance Moved (cm)", rep("", 2), 
								      "log 1m Speed (cm/s)", rep("", 2),
								     "log Burst Speed (cm/s)", rep("", 2)))  %>% 
					select(Species, Trait, contrast, Estimate, Q2.5, Q97.5,pmcmc)  

# Full table
		full2 <- rbind(deli_behav, guich_behav)
	flextable(full2)  %>% autofit()  %>% align(align = "center", part = "all")  
```


```{r, tbl-tbl3}
#| label: tbl-tbl3
#| tbl-cap: Posterior means and 95% credible intervals for the between and within-individual correlations among behavioural traits in Lampropholis delicata and Lampropholis guichenoti. Estimates are from a Bayesian multivariate (multi-response) model.

# Load models
   deli_behav_int_nonSVL <- readRDS(here::here("output/models/", "deli_behav_int_nonSVL.rds"))
	 guich_mv_int_nonSVL <- readRDS(here::here("output/models/", "guich_mv_int_nonSVL.rds"))

# posteriors for correlations
	    post_cor_deli_id <- posterior_samples(deli_behav_int_nonSVL, pars = paste0("^cor"))  %>% posterior_summary()   %>% data.frame()
	post_cor_deli_within <- posterior_samples(deli_behav_int_nonSVL, pars = paste0("^rescor"))  %>% posterior_summary()  %>% data.frame()

	    post_cor_guich_id <- posterior_samples(guich_mv_int_nonSVL, pars = paste0("^cor"))  %>% posterior_summary()  %>% data.frame()
	post_cor_guich_within <- posterior_samples(guich_mv_int_nonSVL, pars = paste0("^rescor"))  %>% posterior_summary() %>% data.frame()

# labels
	names <- c("cor(Emergence Time (s), Time Snout Out (s))",
			   "cor(Emergence Time (s), Distance Moved (cm))",
			   "cor(Time Snout Out (s), Distance Moved (cm))",
			   "cor(Emergence Time (s), 1m Speed (cm/s))",
			   "cor(Time Snout Out (s), 1m Speed (cm/s))",
			   "cor(Distance Moved (cm), 1m Speed (cm/s))",
			   "cor(Emergence Time (s), Burst Speed (cm/s))",
			   "cor(Time Snout Out (s), Burst Speed (cm/s))",
			   "cor(Distance Moved (cm), Burst Speed (cm/s))",
			   "cor(1m Speed (cm/s), Burst Speed (cm/s))")
	species <- c("L. delicata - Between Individual", rep("", 9), "L. delicata - Within Individual", rep("", 9),
				 "L. guichenoti - Between Individual", rep("", 9), "L. guichenoti - Within Individual", rep("", 9))

# build table
	table <- data.frame(Species = species,
						Names = rep(names, 4),
						Estimate = c(post_cor_deli_id$Estimate, post_cor_deli_within$Estimate, post_cor_guich_id$Estimate, post_cor_guich_within$Estimate),
						`2.5 %` = c(post_cor_deli_id$Q2.5, post_cor_deli_within$Q2.5, post_cor_guich_id$Q2.5, post_cor_guich_within$Q2.5),
						`97.5 %` = c(post_cor_deli_id$Q97.5, post_cor_deli_within$Q97.5, post_cor_guich_id$Q97.5, post_cor_guich_within$Q97.5), check.names = FALSE)

# full table
	flextable(table)  %>% autofit()  %>% align(align = "center", part = "all")  
```

```{r, tbl-tblS3}
#| label: tbl-tblS3
#| tbl-cap: Posterior means and 95% credible intervals for the interaction between temperature (Temp) and maternal investment (Invest) along with the main effects of temperature and maternal investment on behavioural and performance traits for *Lampropholis delicata* and *Lampropholis guichenoti*. Main effects are pooled posterior means over each level of second predictor variable. Estimates are from a Bayesian multivariate (multi-response) model controlling for SVL (Z-transformed).

# Load models
             deli_svl <- readRDS(here::here("output/models/", "deli_behav_int.rds"))
	        guich_svl <- readRDS(here::here("output/models/", "guich_mv_int.rds"))

# Build tables
	 deli_behav <- build_behav_table(deli_svl)  %>% 
	 				mutate(Species = c("L. delicata", rep("", 14)),
						Trait = c("log Emergence Time (s)", rep("", 2),
								  "log Time Snout Out (s)", rep("", 2), 
								  "Distance Moved (cm)", rep("", 2), 
								  "log 1m Speed (cm/s)", rep("", 2),
								  "log Burst Speed (cm/s)", rep("", 2)))  %>% 
					select(Species, Trait, contrast, Estimate, Q2.5, Q97.5,pmcmc)
	guich_behav <- build_behav_table(guich_svl)  %>% 
					mutate(Species = c("L. guichenoti", rep("", 14)),
							Trait = c("log Emergence Time (s)", rep("", 2),
								      "log Time Snout Out (s)", rep("", 2), 
								      "Distance Moved (cm)", rep("", 2), 
								      "log 1m Speed (cm/s)", rep("", 2),
								     "log Burst Speed (cm/s)", rep("", 2)))  %>% 
					select(Species, Trait, contrast, Estimate, Q2.5, Q97.5,pmcmc)  

# Full table
		full3 <- rbind(deli_behav, guich_behav)
	flextable(full3)  %>% autofit()  %>% align(align = "center", part = "all")  

```